### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by bitrate16** [Extraltodeus/advanced-loopback-for-sd-webui#5]
Commit: [1296b5f](https://github.com/Extraltodeus/advanced-loopback-for-sd-webui/commit/1296b5f3326c1a1ade031a248338f1487ab439a7)

Traceback:
```
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui-master\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui-master\modules\img2img.py", line 137, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "F:\stable-diffusion-webui-master\modules\scripts.py", line 290, in run
    processed = script.run(p, *script_args)
  File "F:\stable-diffusion-webui-master\scripts\advanced_loopback.py", line 211, in run
    ds = remap_range(get_sin_steps(i,amplify_sine_variation_denoise,phase_diff_denoising),0,1,denoising_strength_min,denoising_strength_max)
  File "F:\stable-diffusion-webui-master\scripts\advanced_loopback.py", line 126, in remap_range
    if value > MaxIn: value = MaxIn;
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Arguments:
```
(0, 'What you will see is 100% artificial', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=512x512 at 0x231AC3B4FA0>, None, None, None, 0, 50, 0, 4, 1, False, False, 100, 8, 7, 0.5, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, False, 32, 0, '', '', 1, 1.0, 1, 1, 0, 0, 5.0, 15.0, 0.2, 0.6, 1, True, True, True, 0.5, False, '', 5, True, 0, 1, False, False, '<p>Running in img2img mode:<br><br>Render these video formats:</p>', '<p style="margin-bottom:0.75em">Animation Parameters</p>', '<p style="margin-bottom:0.75em">Initial Parameters</p>', '<p style="margin-bottom:0.75em">Prompt Template, applied to each keyframe below</p>', '<p style="margin-bottom:0.75em">Props, Stamps</p>', '<p>Supported Keyframes:<br>time_s | source | video, images, img2img | path<br>time_s | prompt | positive_prompts | negative_prompts<br>time_s | template | positive_prompts | negative_prompts<br>time_s | prompt_from_png | file_path<br>time_s | transform | zoom | x_shift | y_shift | rotation<br>time_s | seed | new_seed_int<br>time_s | noise | added_noise_strength<br>time_s | denoise | denoise_value<br>time_s | set_text | textblock_name | text_prompt | x | y | w | h | fore_color | back_color | font_name<br>time_s | clear_text | textblock_name<br>time_s | prop | prop_name | prop_filename | x pos | y pos | scale | rotation<br>time_s | set_stamp | stamp_name | stamp_filename | x pos | y pos | scale | rotation<br>time_s | clear_stamp | stamp_name<br>time_s | col_set<br>time_s | col_clear<br>time_s | model | model</p>', '10.0', '15', False, False, True, '1.0', '', '', '', 0.4, '0', '0', '0', '', False, 0, False, 0.1, True, '<p>Running in img2img mode:<br><br>Render these video formats:</p>', '<p style="margin-bottom:0.75em">Animation Parameters</p>', '<p style="margin-bottom:0.75em">Initial Parameters</p>', '<p style="margin-bottom:0.75em">Prompt Template, applied to each keyframe below</p>', '<p style="margin-bottom:0.75em">Props, Stamps</p>', '<p>Supported Keyframes:<br>time_s | source | video, images, img2img | path<br>time_s | prompt | positive_prompts | negative_prompts<br>time_s | template | positive_prompts | negative_prompts<br>time_s | prompt_from_png | file_path<br>time_s | transform | zoom | x_shift | y_shift | rotation<br>time_s | seed | new_seed_int<br>time_s | noise | added_noise_strength<br>time_s | denoise | denoise_value<br>time_s | set_text | textblock_name | text_prompt | x | y | w | h | fore_color | back_color | font_name<br>time_s | clear_text | textblock_name<br>time_s | prop | prop_name | prop_filename | x pos | y pos | scale | rotation<br>time_s | set_stamp | stamp_name | stamp_filename | x pos | y pos | scale | rotation<br>time_s | clear_stamp | stamp_name<br>time_s | col_set<br>time_s | col_clear<br>time_s | model | model</p>', '10.0', '15', False, False, True, '1.0', '', '', '', 0.4, '0', '0', '0', '', False, 0, False, 0.1, True, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'Show/Hide AlphaCanvas', 384, 'Update Outpainting Size', 8, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, '', 2, '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, 1, '', 0, '', True, False, False) {}
```

Config:
![Screenshot 2022-11-13 at 23-01-16 Stable Diffusion](https://user-images.githubusercontent.com/9000114/201541840-44b21a3e-483f-4e7f-9ca7-83ab6e92f728.png)

**Comment by Extraltodeus** [comment]
Hello,

Could it be because you set up "loops" to only one?

**Comment by bitrate16** [comment]
@Extraltodeus 
Still crash
![Screenshot 2022-11-16 at 00-06-09 Stable Diffusion](https://user-images.githubusercontent.com/9000114/202025292-7b7565ba-eeac-4f5b-8103-09407fc72d41.png)

SD-webui commit: 98947d173e3f1667eba29c904f681047dea9de90

**Comment by bitrate16** [comment]
Issue occurs if you use `Denoising strength proportional change ending value (0.1 = disabled) ` in the same time with `Use sine denoising strength variation`.
Turning off first allows second and vice versa
